/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutOptimizationImport } from './routes/_layout/optimization'
import { Route as LayoutCalculatorImport } from './routes/_layout/calculator'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOptimizationRoute = LayoutOptimizationImport.update({
  path: '/optimization',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCalculatorRoute = LayoutCalculatorImport.update({
  path: '/calculator',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/calculator': {
      preLoaderRoute: typeof LayoutCalculatorImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/optimization': {
      preLoaderRoute: typeof LayoutOptimizationImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutCalculatorRoute,
    LayoutOptimizationRoute,
    LayoutIndexRoute,
  ]),
])

/* prettier-ignore-end */
